feat: add supportUs and some info in info.vue
ColdeGarage/EECamp-web pull request #3
Opened 2022-03-28 15:14 UTC by treeleaves30760

2022-03-29 07:16 UTC, ARui-TW commented on pages/supportUs.vue
> +          src="https://eecampapi.nthuee.org/public/9fd9216f-ab48-48b7-85a6-66ab17fdc27a_NTHUEECamp.jpg"
Don't use this URL directly. Either use the URL saved in Vuex or use up load the picture to sites like Imgur and use that given URL.

2022-03-29 07:16 UTC, ARui-TW commented on pages/supportUs.vue
> +        <h1 class="text-center">支持我們</h1>
Don't use the heading tag to adjust text size. Use parameters defined in 
[`assets/css/typography.scss`](https://github.com/ColdeGarage/EECamp-web/blob/main/assets/css/typography.scss).

2022-03-29 07:16 UTC, ARui-TW commented on pages/supportUs.vue
> +        <h1 class="text-center">支持我們</h1>
Also, don't use text-center. Please use flex.

2022-03-30 12:30 UTC, treeleaves30760 commented on pages/supportUs.vue
> +          src="https://eecampapi.nthuee.org/public/9fd9216f-ab48-48b7-85a6-66ab17fdc27a_NTHUEECamp.jpg"
I decide to use imgur

2022-03-30 17:05 UTC, ARui-TW requested changes

2022-03-30 17:05 UTC, ARui-TW commented on pages/supportUs.vue
> +  <v-container class="">
Remove the empty class

2022-03-30 17:05 UTC, ARui-TW commented on pages/supportUs.vue
> +        <v-row justify="space-around">
You don't need <v-row /> here, use `<div class="d-flex justify-space-around">` will be enough.

2022-03-30 17:05 UTC, ARui-TW commented on pages/supportUs.vue
>          <p class="font-weight-bold p-2">
There is no class `p-2`

2022-03-30 17:05 UTC, ARui-TW commented on pages/supportUs.vue
> +            large
Why use both `x-large` and `large`?

2022-03-30 17:05 UTC, ARui-TW commented on pages/supportUs.vue
> +            large
Same as above.

2022-03-30 17:22 UTC, treeleaves30760 commented
I had changed the code

2022-03-30 17:24 UTC, ARui-TW approved these changes

2022-03-30 17:26 UTC, merged